export const getNewVideos = [
    {
        id: 31064,
        channel_id: "UCdZ7t90tgjwOO9PVhzT5A2g",
        video_id: "rK2XEunUf0c",
        title: "Askalaphos (Greece) - Path of the Serpent (EP) 2021",
        url: "rK2XEunUf0c",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/rK2XEunUf0c/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/rK2XEunUf0c/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/rK2XEunUf0c/hqdefault.jpg",
        channel_title: "Greg Biehl",
        hide: 0,
        deleted: 0,
    },
    {
        id: 31364,
        channel_id: "UCwfonT2RaN3ovsu1Qa22Xbw",
        video_id: "X909C68OqW8",
        title: "TARLUNG - Horses Of Plague  **OFFICIAL VIDEO**",
        url: "X909C68OqW8",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/X909C68OqW8/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/X909C68OqW8/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/X909C68OqW8/hqdefault.jpg",
        channel_title: "ROB HAMMER *stonerdoom*psych*sludge*grunge*metal*",
        hide: 0,
        deleted: 0,
    },
    {
        id: 30917,
        channel_id: "UC7eKF0lPY8LNwfczq9UFlxg",
        video_id: "ycME100YCz8",
        title: "N\u016aR - The Snake (Official Video)",
        url: "ycME100YCz8",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/ycME100YCz8/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/ycME100YCz8/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/ycME100YCz8/hqdefault.jpg",
        channel_title: "666MrDoom",
        hide: 0,
        deleted: 0,
    },
    {
        id: 31313,
        channel_id: "UCtqNS8M6T9KkC1qHDGk7WcQ",
        video_id: "QRYfrLJYNb8",
        title: "TarpitOrchestra - POP (full Album 2021)",
        url: "QRYfrLJYNb8",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/QRYfrLJYNb8/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/QRYfrLJYNb8/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/QRYfrLJYNb8/hqdefault.jpg",
        channel_title: "Rock Freaks [official]",
        hide: 0,
        deleted: 0,
    },
    {
        id: 31413,
        channel_id: "UCzCWehBejA23yEz3zp7jlcg",
        video_id: "l1whTXiaHbg",
        title: "The Devil&#39;s Sermon - Skr\u0119cony W Fa\u0142dy (Track Premiere)",
        url: "l1whTXiaHbg",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/l1whTXiaHbg/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/l1whTXiaHbg/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/l1whTXiaHbg/hqdefault.jpg",
        channel_title: "Black Metal Promotion",
        hide: 0,
        deleted: 0,
    },
    {
        id: 30914,
        channel_id: "UC7eKF0lPY8LNwfczq9UFlxg",
        video_id: "68x_6Fg9zww",
        title: "TarpitOrchestra - POP (Full Album 2021)",
        url: "68x_6Fg9zww",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/68x_6Fg9zww/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/68x_6Fg9zww/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/68x_6Fg9zww/hqdefault.jpg",
        channel_title: "666MrDoom",
        hide: 0,
        deleted: 0,
    },
    {
        id: 30918,
        channel_id: "UC7eKF0lPY8LNwfczq9UFlxg",
        video_id: "os-_5sAjB_U",
        title: "Dawn Fades - Ode (Full Album 2021)",
        url: "os-_5sAjB_U",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/os-_5sAjB_U/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/os-_5sAjB_U/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/os-_5sAjB_U/hqdefault.jpg",
        channel_title: "666MrDoom",
        hide: 0,
        deleted: 0,
    },
    {
        id: 31014,
        channel_id: "UCDLkzWN1rHY4eYkGnVruHVw",
        video_id: "rmbHYCQoCCw",
        title: "Amun - The City (Full album)",
        url: "rmbHYCQoCCw",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/rmbHYCQoCCw/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/rmbHYCQoCCw/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/rmbHYCQoCCw/hqdefault.jpg",
        channel_title: "Atmospheric Black Metal Albums",
        hide: 0,
        deleted: 0,
    },
];

export const getChannelById = [
    {
        id: 2289,
        channel_id: "UCknVpWR6m2Ijzkqo-aPXs_g",
        video_id: "kDzIVCiHbGY",
        title: "Space Slavery - Space Slavery (Full Album)",
        url: "kDzIVCiHbGY",
        published_at: "2021-08-23",
        default_thumbnail: "https://i.ytimg.com/vi/kDzIVCiHbGY/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/kDzIVCiHbGY/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/kDzIVCiHbGY/hqdefault.jpg",
        channel_title: "Stoned Meadow Of Doom",
        hide: 0,
        deleted: 0,
    },
    {
        id: 2290,
        channel_id: "UCknVpWR6m2Ijzkqo-aPXs_g",
        video_id: "qHalkMOY3JA",
        title: "Terminus - The Silent Bell Toll (2021) (New Full Album)",
        url: "qHalkMOY3JA",
        published_at: "2021-08-22",
        default_thumbnail: "https://i.ytimg.com/vi/qHalkMOY3JA/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/qHalkMOY3JA/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/qHalkMOY3JA/hqdefault.jpg",
        channel_title: "Stoned Meadow Of Doom",
        hide: 0,
        deleted: 0,
    },
    {
        id: 2291,
        channel_id: "UCknVpWR6m2Ijzkqo-aPXs_g",
        video_id: "AfQYT9vXQ1g",
        title: "Torchships - Torchships (2021) (New Full Album)",
        url: "AfQYT9vXQ1g",
        published_at: "2021-08-20",
        default_thumbnail: "https://i.ytimg.com/vi/AfQYT9vXQ1g/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/AfQYT9vXQ1g/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/AfQYT9vXQ1g/hqdefault.jpg",
        channel_title: "Stoned Meadow Of Doom",
        hide: 0,
        deleted: 0,
    },
    {
        id: 2292,
        channel_id: "UCknVpWR6m2Ijzkqo-aPXs_g",
        video_id: "VrWYHrPUAjU",
        title: "The Bright Dark - MMXX (2021) (New Full Album)",
        url: "VrWYHrPUAjU",
        published_at: "2021-08-19",
        default_thumbnail: "https://i.ytimg.com/vi/VrWYHrPUAjU/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/VrWYHrPUAjU/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/VrWYHrPUAjU/hqdefault.jpg",
        channel_title: "Stoned Meadow Of Doom",
        hide: 0,
        deleted: 0,
    },
    {
        id: 2293,
        channel_id: "UCknVpWR6m2Ijzkqo-aPXs_g",
        video_id: "qdTOsFUgd0E",
        title: "Familia de Lobos - Familia de Lobos (Full Album)",
        url: "qdTOsFUgd0E",
        published_at: "2021-08-18",
        default_thumbnail: "https://i.ytimg.com/vi/qdTOsFUgd0E/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/qdTOsFUgd0E/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/qdTOsFUgd0E/hqdefault.jpg",
        channel_title: "Stoned Meadow Of Doom",
        hide: 0,
        deleted: 0,
    },
];

export const getAllChannels = [
    {
        id: 16,
        channel_id: "UC7eKF0lPY8LNwfczq9UFlxg",
        channel_title: "666MrDoom",
    },
    {
        id: 17,
        channel_id: "UCCGbKiCJjph8Grazqmo7z4w",
        channel_title: "NWOTHM Full Albums",
    },
    {
        id: 46,
        channel_id: "UCDLkzWN1rHY4eYkGnVruHVw",
        channel_title: "Atmospheric Black Metal Albums",
    },
];

export const getSingleClip = [
    {
        id: 31064,
        channel_id: "UCdZ7t90tgjwOO9PVhzT5A2g",
        video_id: "rK2XEunUf0c",
        title: "Askalaphos (Greece) - Path of the Serpent (EP) 2021",
        url: "rK2XEunUf0c",
        published_at: "2021-09-19",
        default_thumbnail: "https://i.ytimg.com/vi/rK2XEunUf0c/default.jpg",
        medium_thumbnail: "https://i.ytimg.com/vi/rK2XEunUf0c/mqdefault.jpg",
        high_thumbnail: "https://i.ytimg.com/vi/rK2XEunUf0c/hqdefault.jpg",
        channel_title: "Greg Biehl",
        hide: 0,
        deleted: 0,
    },
];
